import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../styles/app.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create-nextjs-starter-kit",
  title: "create-nextjs-starter-kit",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
