name: PR Labeling

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch base branch
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          git fetch origin $BASE_BRANCH:$BASE_BRANCH
          HEAD_BRANCH=${{ github.head_ref }}
          git fetch origin $HEAD_BRANCH:$HEAD_BRANCH

      - name: Get changed files
        id: changed-files
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH=${{ github.head_ref }}
          echo "Base Branch: $BASE_BRANCH"
          echo "Head Branch: $HEAD_BRANCH"
          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH origin/$HEAD_BRANCH)
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
