name: Verify Pull Request Originates from dev Branch

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Error: Pull requests to main must come from the dev branch"
            exit 1
          fi
